from django.urls import path
from django.contrib.auth import views as auth_views
from animals import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.startindex, name='startindex'),
    path('toemoji/', views.toemoji, name='toemoji'),
    path('studypoints/', views.studypoints, name='studypoints'),
    path('animals/', views.animals, name='animals'),
    path('getimage/', views.getimage, name='getimage'),
    path('kirjallisuus/', views.kirjallisuus, name='kirjallisuus'),
    path('stars/', views.stars, name='stars'),
    path('askanything/', views.askanything, name='askanything'),
    path('artquestion/', views.artquestion, name='artquestion'),
    path('tyylitaulu/', views.tyylitaulu, name='tyylitaulu'),
    path('codepython/', views.codepython, name='codepython'),
    path('askbuffet/', views.askbuffet, name='askbuffet'),
    path('schufflecards/', views.schufflecards, name='schufflecards'),
    path('turbomode/', views.turbomode, name='turbomode'),
    path('flushchat/', views.flushchat, name='flushchat'),
    path('chatstories/', views.chatstories, name='chatstories'),
    path('chatmodal/<id>', views.chatmodal, name='chatmodal'),
    path('chatimage/<chat_id>', views.chatimage, name='chatimage'),
    path('rolldicies/', views.rolldicies, name='rolldicies'),
    path('storycubesstory/', views.storycubesstory, name='storycubesstory'),
    path('readoutloud/', views.readoutloud, name='readoutloud'),
    path('storycubesimage/', views.storycubesimage, name='storycubesimage'),
    path('savestory/', views.savestory, name='savestory'),
    path('getscience/', views.getscience, name='getscience'),
    path('justdraw/', views.justdraw, name='justdraw'),
    path('comparedocs/', views.comparedocs, name='comparedocs'),
    path('whatsup/', views.whatsup, name='whatsup'),
    path('analysedoc/', views.analysedoc, name='analysedoc'),
    path('makeanalysis/', views.makeanalysis, name='makeanalysis'),
    path('summarizetext/', views.summarizetext, name='summarizetext'),
    path('imageanaysis/', views.imageanaysis, name='imageanaysis'),
    path('indexexamples/', views.indexexamples, name='indexexamples'),
    path('indexexamples/<str:id>', views.indexexampleopen, name='indexexampleopen'),
]
